# Generated by Django 5.1.5 on 2025-04-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile_studygroup_groupmessage'),
        ('base', '0006_review_user'),
    ]

    operations = [
    ]
